version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "4000"
    networks:
      - webnet

  nginx:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

networks:
  webnet:
